### PR TITLE
Update Yosys.

### PR DESCRIPTION
**Pull request by hzeller**

### CODE REVIEW

**Comment by hzeller** [comment]
@rkapuscik not sure if the failure is due to the new Yosys or if it is some random glitch.

In any case, we should update Yosys, which is already more than half a year old and it is hard to maintain a current setup with an ancient Yosys.

**Comment by hzeller** [comment]
Is there a chance that we get Yosys updated to a more recent version @rkapuscik ?

**Comment by rkapuscik** [comment]
Yes, I've started looking into this. In general new Yosys seems to work (as seen in the CI, even for larger cores), but of course I need to resolve the Ibex regression before updating it.

**Comment by hzeller** [comment]
Any update on this ? By now, my PR is of course already outdated, so I convert it to draft.

The need to update Yosys is still there, we're now already 8 months behind head.

**Comment by mglb** [comment]
@hzeller

An issue is caused by changes related to `RAMB36E1` in `brams_xc6v_map.v`: https://github.com/YosysHQ/yosys/pull/3189/commits/2a6e8b3a7981958b6ab189ea1f65f2b17ef86e9f#diff-3528513f49143fc26f19ac3d5c9b5090e8d9e8436230097bf60dff02ab9c6a05

A few ports seems to be connected differently in some cases. The one mentioned in Vivado's error message is `DIADI`, but there are warnings from yosys for a few other.
Quick look at the diff tells that there were situations where `0` had been assigned to DIADI, but those cases were removed.
Since we patch the ibex sources using https://github.com/antmicro/yosys-systemverilog/blob/master/uhdm-tests/ibex/top_artya7_core.patch there is a possibility that the patch has to be updated.

Error from Vivado:

```
****** Vivado v2017.2 (64-bit)
  **** SW Build 1909853 on Thu Jun 15 18:39:10 MDT 2017
  **** IP Build 1909766 on Thu Jun 15 19:58:00 MDT 2017
    ** Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.

source lowrisc_ibex_top_artya7_surelog_0.1.tcl -notrace
Design is defaulting to srcset: sources_1
Design is defaulting to constrset: constrs_1
Parsing EDIF File [./lowrisc_ibex_top_artya7_surelog_0.1.edif]
INFO: [Common 17-206] Exiting Vivado at Tue Jan 17 11:58:05 2023...
make[1]: Leaving directory '/root/yosys-systemverilog/yosys-systemverilog/UHDM-integration-tests/build/lowrisc_ibex_top_artya7_surelog_0.1/synth-vivado'

ERROR: make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
ERROR: [EDIF 20-86] Cannot find port 'DIADI' on instance 'id00045' of cell 'RAMB36E1' instantiated within cell '$paramod$f4c50e70e423ca6d8f81eb15ae5ff3e26b2b15ff\prim_generic_ram_1p' [/root/yosys-systemverilog/yosys-systemverilog/UHDM-integration-tests/build/lowrisc_ibex_top_artya7_surelog_0.1/synth-vivado/lowrisc_ibex_top_artya7_surelog_0.1.edif:3291]
make[1]: *** [Makefile:6: lowrisc_ibex_top_artya7_surelog_0.1.xpr] Error 1

ERROR: Failed to build lowrisc:ibex:top_artya7_surelog:0.1 : '['make']' exited with an error: 2
make: *** [/root/yosys-systemverilog/yosys-systemverilog/UHDM-integration-tests/../uhdm-tests/ibex/Makefile.in:23: uhdm/yosys/synth-ibex-build] Error 1
```

**Comment by mglb** [comment]
Yosys has been updated, closing.

**Pull request closed without merging**
