### PR TITLE
synth_xilinx -> synth in formal verification

### PR DESCRIPTION
**Pull request by tgorochowik**
There are opinions that yosys is better at comparing non-vendor specific synthesis results when doing formal verification. Let's run this and check the results.

### CODE REVIEW

**Comment by tgorochowik** [comment]
This seems to be getting more new failures than new passes, let's not change that until we have a better reason to.

**Comment by alaindargelas** [comment]
@tgorochowik, I forgot, you also need:

**hierarchy -auto-top**
synth

**Comment by alaindargelas** [comment]
Please try again with these 2 commands instead of "synth_xilinx"

**Comment by tgorochowik** [comment]
Reopening with the additional command added

**Comment by tgorochowik** [comment]
@alaindargelas as you can see in the summary, there are fewer differences, but the total is still worse than synth_xilinx

**Pull request closed without merging**
